In [3]:
import pandas as pd
import numpy as np

In [4]:
df= pd.read_csv('../03.results/outputs/ATOM_USD_ML_features_preprocessed.csv')
df.head()

,date,symbol,last_price,open,high,low,volume,last_return,return_3d,returnvola_3d,...,rsi_14,bb_upper_20,bb_lower_20,bb_width_20,high_low_range_pct,day_of_week,month,Surge,target_next_close,target_next_return
0,2020-01-26,ATOM/USD,4.480,4.379,4.505,4.363,355850.0,0.001148,0.002960,0.043457,...,48.788146,11.611434,8.05182,0.325594,0.032427,6,1,0,4.515,0.007812
1,2020-01-27,ATOM/USD,4.515,4.474,4.672,4.401,1080000.0,0.007812,0.002960,0.043457,...,48.788146,11.611434,8.05182,0.325594,0.060572,0,1,1,4.601,0.019048
2,2020-01-28,ATOM/USD,4.601,4.516,4.609,4.473,577350.0,0.019048,0.002960,0.043457,...,48.788146,11.611434,8.05182,0.325594,0.030115,1,1,1,4.401,-0.043469
3,2020-01-29,ATOM/USD,4.401,4.577,4.597,4.355,1070000.0,-0.043469,-0.017634,0.033327,...,48.788146,11.611434,8.05182,0.325594,0.052873,2,1,0,4.410,0.002045
4,2020-01-30,ATOM/USD,4.410,4.399,4.480,4.307,903250.0,0.002045,-0.023256,0.032324,...,48.788146,11.611434,8.05182,0.325594,0.039327,3,1,0,4.397,-0.002948

In [5]:
#removing the columns which are not required for the model training
df.drop(['date','symbol'], axis=1, inplace=True)
df.head()

,last_price,open,high,low,volume,last_return,return_3d,returnvola_3d,volume_3d,volumevola_3d,...,rsi_14,bb_upper_20,bb_lower_20,bb_width_20,high_low_range_pct,day_of_week,month,Surge,target_next_close,target_next_return
0,4.480,4.379,4.505,4.363,355850.0,0.001148,0.002960,0.043457,1.037463e+07,1.170050e+06,...,48.788146,11.611434,8.05182,0.325594,0.032427,6,1,0,4.515,0.007812
1,4.515,4.474,4.672,4.401,1080000.0,0.007812,0.002960,0.043457,1.037463e+07,1.170050e+06,...,48.788146,11.611434,8.05182,0.325594,0.060572,0,1,1,4.601,0.019048
2,4.601,4.516,4.609,4.473,577350.0,0.019048,0.002960,0.043457,2.013200e+06,3.710599e+05,...,48.788146,11.611434,8.05182,0.325594,0.030115,1,1,1,4.401,-0.043469
3,4.401,4.577,4.597,4.355,1070000.0,-0.043469,-0.017634,0.033327,2.727350e+06,2.873619e+05,...,48.788146,11.611434,8.05182,0.325594,0.052873,2,1,0,4.410,0.002045
4,4.410,4.399,4.480,4.307,903250.0,0.002045,-0.023256,0.032324,2.550600e+06,2.505728e+05,...,48.788146,11.611434,8.05182,0.325594,0.039327,3,1,0,4.397,-0.002948

In [6]:
#feature names
print(df.columns)

Index(['last_price', 'open', 'high', 'low', 'volume', 'last_return',
       'return_3d', 'returnvola_3d', 'volume_3d', 'volumevola_3d', 'return_7d',
       'returnvola_7d', 'volume_7d', 'volumevola_7d', 'return_14d',
       'returnvola_14d', 'volume_14d', 'volumevola_14d', 'return_21d',
       'returnvola_21d', 'volume_21d', 'volumevola_21d', 'return_30d',
       'returnvola_30d', 'volume_30d', 'volumevola_30d', 'return_60d',
       'returnvola_60d', 'volume_60d', 'volumevola_60d', 'return_90d',
       'returnvola_90d', 'volume_90d', 'volumevola_90d', 'sma_7', 'sma_14',
       'sma_30', 'sma_50', 'sma_90', 'sma_200', 'ema_12', 'ema_26', 'macd',
       'macd_signal', 'rsi_14', 'bb_upper_20', 'bb_lower_20', 'bb_width_20',
       'high_low_range_pct', 'day_of_week', 'month', 'Surge',
       'target_next_close', 'target_next_return'],
      dtype='str')

In [7]:
#change features names
features = { 'return_3d':'3day_return', 'returnvola_3d':'3day_return_volatility', 'volume_3d':'3day_volume',                    'volumevola_3d':'3day_volume_volatility', 'return_7d':'7day_return',
       'returnvola_90d': '90day_return_volatility', 'volume_90d': '90day_volume', 'volumevola_90d': '90day_volume_volatility', 'sma_7': '7day_Simple_Moving_Average', 'sma_14': '14day_Simple_Moving_Average', 'sma_30': '30day_Simple_Moving_Average', 'sma_50': '50day_Simple_Moving_Average', 'sma_90': '90day_Simple_Moving_Average', 'sma_200': '200day_Simple_Moving_Average', 'ema_12': '12day_Exponential_Moving_Average', 'ema_26': '26day_Exponential_Moving_Average', 'macd': 'Moving_Average_Convergence_Divergence_value',
       'macd_signal': 'Moving_Average_Convergence_Divergence_signal_value', 'rsi_14': '14day_Relative_Strength_Index', 'bb_upper_20': '20day_Bollinger_Bands_Upper_Band', 'bb_lower_20': '20day_Bollinger_Bands_Lower_Band', 'bb_width_20': '20day_Bollinger_Bands_Width',
       'high_low_range_pct': 'high_low_range_percentage', 'day_of_week': 'day_of_week', 'month': 'month', 'Surge': 'surge_flag',
       'target_next_close': 'next_day_close_price', 'target_next_return': 'next_day_return_percentage'} 

df.rename(columns=features, inplace=True)

In [8]:
df.head().T

,0,1,2,3,4
last_price,4.480000e+00,4.515000e+00,4.601000e+00,4.401000e+00,4.410000e+00
open,4.379000e+00,4.474000e+00,4.516000e+00,4.577000e+00,4.399000e+00
high,4.505000e+00,4.672000e+00,4.609000e+00,4.597000e+00,4.480000e+00
low,4.363000e+00,4.401000e+00,4.473000e+00,4.355000e+00,4.307000e+00
volume,3.558500e+05,1.080000e+06,5.773500e+05,1.070000e+06,9.032500e+05
last_return,1.148041e-03,7.812500e-03,1.904762e-02,-4.346881e-02,2.044990e-03
3day_return,2.959654e-03,2.959654e-03,2.959654e-03,-1.763393e-02,-2.325581e-02
3day_return_volatility,4.345704e-02,4.345704e-02,4.345704e-02,3.332743e-02,3.232362e-02
3day_volume,1.037463e+07,1.037463e+07,2.013200e+06,2.727350e+06,2.550600e+06
3day_volume_volatility,1.170050e+06,1.170050e+06,3.710599e+05,2.873619e+05,2.505728e+05
7day_return,6.517376e-03,6.517376e-03,6.517376e-03,6.517376e-03,6.517376e-03
returnvola_7d,4.713923e-02,4.713923e-02,4.713923e-02,4.713923e-02,4.713923e-02
volume_7d,2.423003e+07,2.423003e+07,2.423003e+07,2.423003e+07,2.423003e+07
volumevola_7d,1.557346e+06,1.557346e+06,1.557346e+06,1.557346e+06,1.557346e+06
return_14d,1.337935e-02,1.337935e-02,1.337935e-02,1.337935e-02,1.337935e-02
returnvola_14d,4.857584e-02,4.857584e-02,4.857584e-02,4.857584e-02,4.857584e-02
volume_14d,4.853852e+07,4.853852e+07,4.853852e+07,4.853852e+07,4.853852e+07
volumevola_14d,1.891471e+06,1.891471e+06,1.891471e+06,1.891471e+06,1.891471e+06
return_21d,2.128511e-02,2.128511e-02,2.128511e-02,2.128511e-02,2.128511e-02
returnvola_21d,4.923668e-02,4.923668e-02,4.923668e-02,4.923668e-02,4.923668e-02
volume_21d,7.291683e+07,7.291683e+07,7.291683e+07,7.291683e+07,7.291683e+07
volumevola_21d,2.130875e+06,2.130875e+06,2.130875e+06,2.130875e+06,2.130875e+06
return_30d,3.057323e-02,3.057323e-02,3.057323e-02,3.057323e-02,3.057323e-02
returnvola_30d,4.981039e-02,4.981039e-02,4.981039e-02,4.981039e-02,4.981039e-02
volume_30d,1.043686e+08,1.043686e+08,1.043686e+08,1.043686e+08,1.043686e+08
volumevola_30d,2.371430e+06,2.371430e+06,2.371430e+06,2.371430e+06,2.371430e+06
return_60d,7.890098e-02,7.890098e-02,7.890098e-02,7.890098e-02,7.890098e-02
returnvola_60d,NaN,NaN,NaN,NaN,NaN
volume_60d,2.100086e+08,2.100086e+08,2.100086e+08,2.100086e+08,2.100086e+08
volumevola_60d,2.909781e+06,2.909781e+06,2.909781e+06,2.909781e+06,2.909781e+06
return_90d,1.245967e-01,1.245967e-01,1.245967e-01,1.245967e-01,1.245967e-01
90day_return_volatility,5.112403e-02,5.112403e-02,5.112403e-02,5.112403e-02,5.112403e-02
90day_volume,3.172320e+08,3.172320e+08,3.172320e+08,3.172320e+08,3.172320e+08
90day_volume_volatility,3.281948e+06,3.281948e+06,3.281948e+06,3.281948e+06,3.281948e+06
7day_Simple_Moving_Average,9.795559e+00,9.795559e+00,9.795559e+00,9.795559e+00,9.795559e+00
14day_Simple_Moving_Average,9.815007e+00,9.815007e+00,9.815007e+00,9.815007e+00,9.815007e+00
30day_Simple_Moving_Average,9.859409e+00,9.859409e+00,9.859409e+00,9.859409e+00,9.859409e+00
50day_Simple_Moving_Average,9.917820e+00,9.917820e+00,9.917820e+00,9.917820e+00,9.917820e+00
90day_Simple_Moving_Average,1.004909e+01,1.004909e+01,1.004909e+01,1.004909e+01,1.004909e+01
200day_Simple_Moving_Average,1.043346e+01,1.043346e+01,1.043346e+01,1.043346e+01,1.043346e+01
12day_Exponential_Moving_Average,4.480000e+00,4.485385e+00,4.503172e+00,4.487453e+00,4.475537e+00
26day_Exponential_Moving_Average,4.480000e+00,4.482593e+00,4.491364e+00,4.484670e+00,4.479139e+00
Moving_Average_Convergence_Divergence_value,0.000000e+00,2.792023e-03,1.180809e-02,2.782972e-03,-3.601752e-03
Moving_Average_Convergence_Divergence_signal_value,0.000000e+00,5.584046e-04,2.808341e-03,2.803267e-03,1.522263e-03
14day_Relative_Strength_Index,4.878815e+01,4.878815e+01,4.878815e+01,4.878815e+01,4.878815e+01
20day_Bollinger_Bands_Upper_Band,1.161143e+01,1.161143e+01,1.161143e+01,1.161143e+01,1.161143e+01
20day_Bollinger_Bands_Lower_Band,8.051820e+00,8.051820e+00,8.051820e+00,8.051820e+00,8.051820e+00
20day_Bollinger_Bands_Width,3.255941e-01,3.255941e-01,3.255941e-01,3.255941e-01,3.255941e-01
high_low_range_percentage,3.242749e-02,6.057219e-02,3.011515e-02,5.287306e-02,3.932712e-02
day_of_week,6.000000e+00,0.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00
month,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
surge_flag,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00
next_day_close_price,4.515000e+00,4.601000e+00,4.401000e+00,4.410000e+00,4.397000e+00
next_day_return_percentage,7.812500e-03,1.904762e-02,-4.346881e-02,2.044990e-03,-2.947846e-03

In [9]:
df.head()

,last_price,open,high,low,volume,last_return,3day_return,3day_return_volatility,3day_volume,3day_volume_volatility,...,14day_Relative_Strength_Index,20day_Bollinger_Bands_Upper_Band,20day_Bollinger_Bands_Lower_Band,20day_Bollinger_Bands_Width,high_low_range_percentage,day_of_week,month,surge_flag,next_day_close_price,next_day_return_percentage
0,4.480,4.379,4.505,4.363,355850.0,0.001148,0.002960,0.043457,1.037463e+07,1.170050e+06,...,48.788146,11.611434,8.05182,0.325594,0.032427,6,1,0,4.515,0.007812
1,4.515,4.474,4.672,4.401,1080000.0,0.007812,0.002960,0.043457,1.037463e+07,1.170050e+06,...,48.788146,11.611434,8.05182,0.325594,0.060572,0,1,1,4.601,0.019048
2,4.601,4.516,4.609,4.473,577350.0,0.019048,0.002960,0.043457,2.013200e+06,3.710599e+05,...,48.788146,11.611434,8.05182,0.325594,0.030115,1,1,1,4.401,-0.043469
3,4.401,4.577,4.597,4.355,1070000.0,-0.043469,-0.017634,0.033327,2.727350e+06,2.873619e+05,...,48.788146,11.611434,8.05182,0.325594,0.052873,2,1,0,4.410,0.002045
4,4.410,4.399,4.480,4.307,903250.0,0.002045,-0.023256,0.032324,2.550600e+06,2.505728e+05,...,48.788146,11.611434,8.05182,0.325594,0.039327,3,1,0,4.397,-0.002948

In [10]:
#split the data into train and test sets
from sklearn.model_selection import train_test_split

In [ ]:
X = df.drop(['next_day_close_price', 'next_day_return_percentage'], axis=1)
y = df['next_day_return_percentage']

In [12]:
X.head()

,last_price,open,high,low,volume,last_return,3day_return,3day_return_volatility,3day_volume,3day_volume_volatility,...,Moving_Average_Convergence_Divergence_value,Moving_Average_Convergence_Divergence_signal_value,14day_Relative_Strength_Index,20day_Bollinger_Bands_Upper_Band,20day_Bollinger_Bands_Lower_Band,20day_Bollinger_Bands_Width,high_low_range_percentage,day_of_week,month,surge_flag
0,4.480,4.379,4.505,4.363,355850.0,0.001148,0.002960,0.043457,1.037463e+07,1.170050e+06,...,0.000000,0.000000,48.788146,11.611434,8.05182,0.325594,0.032427,6,1,0
1,4.515,4.474,4.672,4.401,1080000.0,0.007812,0.002960,0.043457,1.037463e+07,1.170050e+06,...,0.002792,0.000558,48.788146,11.611434,8.05182,0.325594,0.060572,0,1,1
2,4.601,4.516,4.609,4.473,577350.0,0.019048,0.002960,0.043457,2.013200e+06,3.710599e+05,...,0.011808,0.002808,48.788146,11.611434,8.05182,0.325594,0.030115,1,1,1
3,4.401,4.577,4.597,4.355,1070000.0,-0.043469,-0.017634,0.033327,2.727350e+06,2.873619e+05,...,0.002783,0.002803,48.788146,11.611434,8.05182,0.325594,0.052873,2,1,0
4,4.410,4.399,4.480,4.307,903250.0,0.002045,-0.023256,0.032324,2.550600e+06,2.505728e+05,...,-0.003602,0.001522,48.788146,11.611434,8.05182,0.325594,0.039327,3,1,0

In [13]:
y.head()

0    0.007812
1    0.019048
2   -0.043469
3    0.002045
4   -0.002948
Name: next_day_return_percentage, dtype: float64

In [14]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
#save the train and test sets to csv files
X_train.to_csv('../03.results/outputs/X_train.csv', index=False)
X_test.to_csv('../03.results/outputs/X_test.csv', index=False)
y_train.to_csv('../03.results/outputs/y_train.csv', index=False)
y_test.to_csv('../03.results/outputs/y_test.csv', index=False)