In [2]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor

In [3]:
#load the dataset
X_train = pd.read_csv('../../03.results/outputs/X_train.csv')
X_test = pd.read_csv('../../03.results/outputs/X_test.csv')
y_train = pd.read_csv('../../03.results/outputs/y_train.csv')
y_test = pd.read_csv('../../03.results/outputs/y_test.csv')

In [4]:
X_train.head()

,last_price,open,high,low,volume,last_return,3day_return,3day_return_volatility,3day_volume,3day_volume_volatility,...,Moving_Average_Convergence_Divergence_value,Moving_Average_Convergence_Divergence_signal_value,14day_Relative_Strength_Index,20day_Bollinger_Bands_Upper_Band,20day_Bollinger_Bands_Lower_Band,20day_Bollinger_Bands_Width,high_low_range_percentage,day_of_week,month,surge_flag
0,4.261,4.261,4.443,4.075,3120000.0,0.001175,0.024033,0.028805,7280000.0,632877.028605,...,-0.231823,-0.230354,40.657312,5.093762,4.069938,0.223452,0.086365,4,3,1
1,1.965,1.852,1.989,1.846,2520000.0,0.060443,-0.017009,0.057172,9050000.0,678699.737244,...,-0.170530,-0.159979,37.336245,2.485876,1.873224,0.281091,0.077214,4,12,1
2,11.012,10.826,11.277,10.669,2620000.0,0.017275,-0.053220,0.037552,9380000.0,635714.820761,...,-0.189856,-0.022877,42.396088,12.892284,10.648716,0.190609,0.056161,3,4,1
3,5.096,5.113,5.197,5.012,1340000.0,-0.001567,0.002360,0.037351,6290000.0,658508.415537,...,0.025070,-0.019348,63.528336,5.428371,4.344829,0.221737,0.036182,3,11,0
4,4.409,4.313,4.442,4.275,2950000.0,0.022970,0.062666,0.041046,8340000.0,759407.663908,...,-0.072201,-0.096086,45.721925,4.801232,3.785168,0.236668,0.038720,2,4,1

In [5]:
X_test.head()

,last_price,open,high,low,volume,last_return,3day_return,3day_return_volatility,3day_volume,3day_volume_volatility,...,Moving_Average_Convergence_Divergence_value,Moving_Average_Convergence_Divergence_signal_value,14day_Relative_Strength_Index,20day_Bollinger_Bands_Upper_Band,20day_Bollinger_Bands_Lower_Band,20day_Bollinger_Bands_Width,high_low_range_percentage,day_of_week,month,surge_flag
0,4.214,4.511,4.519,4.214,1520000.0,-0.065425,-0.049188,0.051908,5190000.0,2.007486e+05,...,-0.089036,-0.089326,39.306667,4.918069,4.005931,0.204423,0.067613,3,6,0
1,9.247,9.436,9.436,9.183,1230000.0,-0.019094,0.008177,0.021207,2754500.0,2.969966e+05,...,-0.025745,-0.042136,51.083916,9.814803,8.846997,0.103720,0.026812,0,7,0
2,36.230,33.840,36.240,33.490,3830000.0,0.069994,-0.027121,0.082802,12390000.0,3.746999e+05,...,2.776397,3.732664,49.188373,44.968604,28.075396,0.462549,0.081265,3,9,1
3,1.511,1.513,1.530,1.490,1150000.0,-0.000661,-0.033887,0.014827,3570000.0,3.464102e+04,...,-0.053335,-0.058795,30.973451,1.618670,1.503230,0.073955,0.026438,4,7,0
4,12.663,12.378,12.899,12.378,2650000.0,0.023604,0.072499,0.014156,8420000.0,1.053771e+06,...,0.114252,-0.088587,78.862701,12.380535,10.484565,0.165840,0.042091,6,4,1

In [6]:
y_train.head()

   next_day_return_percentage
0                   -0.035672
1                    0.009160
2                   -0.010625
3                    0.033752
4                    0.032207

In [7]:
y_test.head()

   next_day_return_percentage
0                   -0.019696
1                   -0.005191
2                    0.044714
3                   -0.008604
4                   -0.024402

In [ ]:
basemodel = DecisionTreeRegressor()
basemodel.fit(X_train, y_train)
y_pred = basemodel.predict(X_test)

In [12]:
# Evaluate the model
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Mean Squared Error: 0.005385131591277395
R-squared: -0.4949743524849086